### ISSUE TITLE
[Feature] ANSI Color Codes on Windows

### ISSUE THREAD

**Issue by Froggo8311** [Froggo8311/Phoenix#3]
**Is your feature request related to a problem? Please describe.**
ANSI color codes can not be interpreted on windows. We will change our color providing
method to use the Colorama. I believe the original intention was only to keep the imported
modules to a minimum and only add the used codes to the source for the sake of file size,
but this can be easily changed.

**Comment by Naln1** [comment]
Perhaps just use a modified version of [`gib`'s colors.py](https://sourceforge.net/p/gib-pkg/git/ci/master/tree/colors.py) instead. It'd be much lighter weight and not require an external library.

**Comment by Naln1** [comment]
Actually it seems that you basically are doing that? So I have no idea why it's not working on Binbows...

**Comment by Froggo8311** [comment]
Well so Winblows has a special encoding, and doesn't support ANSI (like the UNIX-like systems do). The colorama module magically detects the proper encoding and does that stuff, but I've kept pushing it off

**Comment by Froggo8311** [comment]
Probably color.py has the windows encoding too

**Comment by Naln1** [comment]
Nu, I wrote colors.py, it just uses the ANSI sequences...
